cfg: models/TR1-SPPCSP-CSP2.yaml
data: data/coco.yaml
hyp: ''
epochs: 100
batch_size: 24
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
weights: ''
name: v4s-TR4-SPPCSP-CSP2
device: '3'
multi_scale: false
single_cls: false
sync_bn: false
local_rank: -1
total_batch_size: 24
world_size: 1
